### ISSUE TITLE
Selenium tests doesn't work

### ISSUE THREAD

**Issue by sippsack** [jugda/dukecon_server#42]
https://dev.dukecon.org/jenkins/job/dukecon_server_develop/org.dukecon$dukecon-server-springboot/471/testReport/junit/org.dukecon.server.gui/DetailPageTest/should_show_details_page/

Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(Capabilities): org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}

Probably a problem with firefox version, needs at least 47.0.1.

**Comment by ahus1** [comment]
locally it now works with the latest version of firefox - but not on the server yet. I'll have another look at it on the server. Server is running on Firefox 46, latest version is Firefox 47

**Comment by ahus1** [comment]
There is a known problem with Firefox 47.0.0 that has been fixed in Firefox 47.0.1. https://github.com/SeleniumHQ/selenium/issues/2110.

The fixed version is not yet available for Ubuntu. 

@ascheman: I've installed Firefox 47.0.1 in /opt/mozilla-firefox and used `update-alternatives` to point the firefox command to the new firefox installation. This will probably not survive the next firefox package update on the machine - but let's wait and see.
